## Тема “Вычисления с помощью Numpy”

In [ ]:
import numpy as np

Задание 1

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [22]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
mean_a = a.mean(0)
mean_a

array([2. , 8.4])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [23]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [33]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1] 
a_centered_sp / (5-1)

2.0

Задание 4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [39]:
np.cov(np.transpose(a))

array([[1. , 2. ],
       [2. , 4.3]])

## Тема “Работа с данными в Pandas”

Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']

In [54]:
import pandas as pd

authors = pd.DataFrame({"author_id": [1, 2, 3], "author_name": ['Тургенев', 'Чехов', 'Островский']})
book = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3], 
                     "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     "price": [450, 220, 999, 234, 500, 600, 724]})

Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [55]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    220
2          1    Тургенев     Дворянское гнездо    999
3          2       Чехов      Толстый и тонкий    234
4          2       Чехов       Дама с собачкой    500
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    724

Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [65]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name            book_title  price
2          1    Тургенев     Дворянское гнездо    999
6          3  Островский  Таланты и поклонники    724
5          3  Островский                 Гроза    600
4          2       Чехов       Дама с собачкой    500
0          1    Тургенев           Отцы и дети    450

Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [72]:
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean']).reset_index().rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        600        724  662.000000
1    Тургенев        220        999  556.333333
2       Чехов        234        500  367.000000

Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [127]:
authors_price["cover"] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
book_info = authors_price.pivot_table(index = 'author_name', columns = 'cover', values = 'price', aggfunc = 'sum', fill_value = 0)
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
print('Датафреймы идентичны') if book_info.equals(book_info2) else print('Что-то пошло не так')

Датафреймы идентичны
